server:
  shutdown: graceful
  forward-headers-strategy: framework
  max-http-request-header-size: 1MB
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
  port: 8080
spring:
  application:
    name: OkvedPhoneMatcher
okved-phone-mather:
  okved-source:
    url: "https://raw.githubusercontent.com/bergstar/testcase/refs/heads/master/"
    file-name: "okved.json"